datadb:
  image: debian:wheezy
  volumes:
    - /var/lib/postgresql
  command: /bin/true

datamedia:
  image: debian:wheezy
  volumes:
    - ./examples/sandbox/media:/media
  command: /bin/true

datastatic:
  image: debian:wheezy
  volumes:
    - /var/www/static
  command: true

datalog:
  image: debian:wheezy
  volumes:
    - /var/log/nginx
    - /var/log/postgres
  command: /bin/true

db:
  image: postgres
  volumes_from:
    - datadb

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./examples/deploy/nginx/sites-enabled/app.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - datastatic
    - datamedia
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  volumes_from:
    - datastatic
    - datamedia
  command: /bin/sh /opt/TimeSide/examples/deploy/start_app.sh
  expose:
    - "80" #default runserver wsgi port