datadb:
  image: debian:stable
  volumes:
    - /var/lib/postgresql
  command: /bin/true

datastatic:
  image: debian:stable
  volumes:
    - /var/www
  command: /bin/true

datalog:
  image: debian:stable
  volumes:
    - /var/log/nginx
    - /var/log/postgres
  command: /bin/true

db:
  image: postgres
  volumes_from:
    - datadb

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./examples/deploy/nginx/sites-enabled:/etc/nginx/sites-enabled
    - /media
  volumes_from:
    - datastatic
    - datalog
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  volumes_from:
    - datastatic
  command: uwsgi --ini /opt/TimeSide/examples/sandbox/uwsgi.ini:local
  ports:
    - "8000:8000"
