data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql


db:
  image: postgres
  volumes_from:
    - data

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./examples/deploy/nginx/sites-enabled:/etc/nginx/sites-enabled
    - /media
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  command: uwsgi --ini /opt/TimeSide/examples/sandbox/uwsgi.ini:local
  ports:
    - "8000:8000"
