media:
  image: debian:wheezy
  volumes:
    - ./examples/sandbox/media:/media
  command: /bin/true

static:
  image: debian:wheezy
  volumes:
    - /var/www/static
  command: true

log:
  image: debian:wheezy
  volumes:
    - /var/log/nginx
    - /var/log/postgres
    - /var/log/uwsgi
  command: /bin/true

# datadb:
#   image: debian:wheezy
#   volumes:
#     - /var/lib/postgresql
#   command: /bin/true

# db:
#   image: postgres
#   volumes_from:
#     - datadb

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./examples/deploy/nginx/sites-enabled/app.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - static
    - media
    - log
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  volumes_from:
    - static
    - media
    - log
  command: /bin/sh /opt/TimeSide/examples/deploy/start_app.sh
  ports:
    - "9000:9000"
  expose:
    - "80" #default runserver wsgi port