data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql
 
db:
  image: postgres
  volumes_from:
    - data

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./examples/deploy/nginx-app.conf:/etc/nginx/sites-enabled/
    #  --> media
    #  --> static
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  command:
    - /opt/TimeSide/examples/sandbox/manage.py syncdb --noinput
    - /opt/TimeSide/examples/sandbox/manage.py migrate --noinput
    - /opt/TimeSide/examples/sandbox/manage.py collectstatic --noinput
  ports:
    - "8000:8000"
