data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql
 
db:
  image: postgres
  volumes_from:
    - data

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./examples/deploy/nginx-app.conf:/etc/nginx/sites-enabled/
    - /var/www/static
    - /media
  links:
    - app

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  command: uwsgi --ini /opt/TimeSide/examples/sandbox/uwsgi.ini
  ports:
    - "8000:8000"
 
